---
- name: Service httpd when no running
  hosts: web
  become: true
  remote_user: devops
  tasks:
  - name: state check web
    command: "systemctl is-active httpd"
    register: fooresult
    ignore_errors: true
  - name: print
    debug:
      var: fooresult.rc
  - name: restart web
    service:
      name: httpd
      state: started
    when: fooresult.rc != 0
